field.storage_settings.rethinkdb:
  type: mapping
  label: 'RethinkDB reference storage settings'
  mapping:
    target_type:
      type: string
      label: 'Type of entity to reference'
    handler:
      type: string
      label: 'Type of entity to reference'
    handler_settings:
      type: string
      label: 'Type of entity to reference'

field.field_settings.rethinkdb:
  type: mapping
  label: 'RethinkDB refernec field settings'
  mapping:
    handler:
      type: string
      label: 'Type of entity to reference'
    handler_settings:
      type: mapping
      mapping:
        search_key:
          type: string
          label: 'foo'

rethinkdb.database:
  type: config_object
  label: 'RethinkDB Config config'
  mapping:
    host:
      type: string
      label: 'Host'
    port:
      type: integer
      label: 'Port'
    database:
      type: string
      label: 'Database'
    api_key:
      type: string
      label: 'API key'
    timeout:
      type: integer
      label: 'Connection time out'
