rethinkdb.database:
  type: config_object
  label: 'RethinkDB Config config'
  mapping:
    host:
      type: string
      label: 'Host'
    port:
      type: integer
      label: 'Port'
    database:
      type: string
      label: 'Database'
    api_key:
      type: string
      label: 'API key'
    timeout:
      type: integer
      label: 'Connection time out'
