<?php

/**
 * @file
 * Contains rethinkdb_websocket.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rethinkdb_websocket_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rethinkdb_websocket module.
    case 'help.page.rethinkdb_websocket':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide a websoket demo using Horizon.js') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rethinkdb_websocket_theme() {
  $theme = [];

  return $theme;
}
