<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitddf6d505bedfbde6b503607dad3bd79c
{
    public static $files = array (
        '53727df1792e6f8400ce2ffc30cbe203' => __DIR__ . '/..' . '/danielmewes/php-rql/rdb/rdb.php',
    );

    public static $prefixLengthsPsr4 = array (
        'r' => 
        array (
            'r\\Tests\\' => 8,
            'r\\' => 2,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'r\\Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/danielmewes/php-rql/tests',
        ),
        'r\\' => 
        array (
            0 => __DIR__ . '/..' . '/danielmewes/php-rql/rdb',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitddf6d505bedfbde6b503607dad3bd79c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitddf6d505bedfbde6b503607dad3bd79c::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
