<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    '53727df1792e6f8400ce2ffc30cbe203' => $vendorDir . '/danielmewes/php-rql/rdb/rdb.php',
);
