<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'r\\Tests\\' => array($vendorDir . '/danielmewes/php-rql/tests'),
    'r\\' => array($vendorDir . '/danielmewes/php-rql/rdb'),
);
